common: &common
  access_key_id: AKIAITWCJUBUVR5Y42TA
  secret_access_key: your/MTWsLVVYy27zngxpAKglk5N8mvmOasKRkH1vux3E+here

development:
  <<: *common
  bucket: apm-assets-dev

test:
  <<: *common
  bucket: apm-assets-test

production:
  <<: *common
  bucket: apm-assets
  